package com.github.hgdcoder.flowershow.push;

public enum PushErrorCode {
    UNREGISTERED,
    SENDER_ID_MISMATCH,
    QUOTA_EXCEEDED,
    UNAVAILABLE,
    INTERNAL,
    TRANSPORT_ERROR,
    INVALID_ARGUMENT,
    CREDENTIALS,
    AUTHENTICATION,
    THIRD_PARTY_AUTH,
    PERMISSION_DENIED,
    CONFIGURATION,
    PERMANENT_FCM_ERROR,
    PROVIDER_NOT_CONFIGURED
}
