create table chat_conversations (
    id varchar(64) primary key,
    conversation_type varchar(20) not null,
    name varchar(120),
    owner_user_id varchar(64),
    direct_user_one_id varchar(64),
    direct_user_two_id varchar(64),
    last_message_id varchar(64),
    last_message_sequence bigint,
    last_message_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uq_chat_direct_users unique (direct_user_one_id, direct_user_two_id),
    constraint fk_chat_conversation_owner foreign key (owner_user_id) references users(id),
    constraint fk_chat_direct_user_one foreign key (direct_user_one_id) references users(id),
    constraint fk_chat_direct_user_two foreign key (direct_user_two_id) references users(id),
    constraint ck_chat_conversation_type check (conversation_type in ('direct', 'group')),
    constraint ck_chat_conversation_shape check (
        (
            conversation_type = 'direct'
            and name is null
            and owner_user_id is null
            and direct_user_one_id is not null
            and direct_user_two_id is not null
            and direct_user_one_id < direct_user_two_id
        )
        or
        (
            conversation_type = 'group'
            and name is not null
            and length(trim(name)) > 0
            and owner_user_id is not null
            and direct_user_one_id is null
            and direct_user_two_id is null
        )
    )
);

create table chat_conversation_members (
    conversation_id varchar(64) not null,
    user_id varchar(64) not null,
    member_role varchar(20) not null default 'member',
    member_state varchar(20) not null default 'active',
    last_read_message_sequence bigint not null default 0,
    last_read_at timestamp,
    joined_at timestamp not null default current_timestamp,
    left_at timestamp,
    primary key (conversation_id, user_id),
    constraint fk_chat_member_conversation foreign key (conversation_id)
        references chat_conversations(id) on delete cascade,
    constraint fk_chat_member_user foreign key (user_id) references users(id),
    constraint ck_chat_member_role check (member_role in ('owner', 'member')),
    constraint ck_chat_member_state check (member_state in ('active', 'left', 'removed')),
    constraint ck_chat_member_state_time check (
        (member_state = 'active' and left_at is null)
        or (member_state <> 'active' and left_at is not null)
    ),
    constraint ck_chat_member_read_sequence check (last_read_message_sequence >= 0)
);

create table chat_messages (
    sequence_no bigint generated by default as identity,
    id varchar(64) primary key,
    conversation_id varchar(64) not null,
    sender_user_id varchar(64) not null,
    message_type varchar(20) not null,
    body text,
    shared_content_id varchar(64),
    client_message_id varchar(128) not null,
    created_at timestamp not null default current_timestamp,
    constraint uq_chat_message_sequence unique (sequence_no),
    constraint uq_chat_message_client unique (
        conversation_id,
        sender_user_id,
        client_message_id
    ),
    constraint fk_chat_message_conversation foreign key (conversation_id)
        references chat_conversations(id) on delete cascade,
    constraint fk_chat_message_sender foreign key (sender_user_id) references users(id),
    constraint fk_chat_message_content foreign key (shared_content_id) references content_items(id),
    constraint ck_chat_message_type check (message_type in ('text', 'video_share')),
    constraint ck_chat_message_shape check (
        (
            message_type = 'text'
            and body is not null
            and length(trim(body)) > 0
            and shared_content_id is null
        )
        or
        (
            message_type = 'video_share'
            and body is null
            and shared_content_id is not null
        )
    ),
    constraint ck_chat_client_message_id check (length(trim(client_message_id)) > 0)
);

alter table chat_conversations
    add constraint fk_chat_last_message foreign key (last_message_id)
        references chat_messages(id) on delete set null;

create index idx_chat_members_user_state
    on chat_conversation_members(user_id, member_state, conversation_id);

create index idx_chat_members_conversation_state
    on chat_conversation_members(conversation_id, member_state, joined_at);

create index idx_chat_messages_history
    on chat_messages(conversation_id, sequence_no desc);

create index idx_chat_messages_unread
    on chat_messages(conversation_id, sequence_no, sender_user_id);

create index idx_chat_conversations_activity
    on chat_conversations(last_message_at desc, id desc);
