create table users (
    id varchar(64) primary key,
    nickname varchar(80) not null,
    avatar_url text,
    bio varchar(255),
    location varchar(80),
    source varchar(30) not null default 'app',
    source_user_id varchar(128),
    created_at timestamp not null default current_timestamp
);

create table content_items (
    id varchar(64) primary key,
    type varchar(20) not null,
    title varchar(255) not null,
    description text,
    author_user_id varchar(64) not null,
    cover_url text,
    source_url text,
    status varchar(20) not null default 'published',
    visibility varchar(20) not null default 'public',
    publish_time bigint,
    raw_json text,
    created_at timestamp not null default current_timestamp,
    constraint fk_content_author foreign key (author_user_id) references users(id)
);

create table content_tags (
    content_id varchar(64) not null,
    tag varchar(80) not null,
    sort_order int not null default 0,
    primary key (content_id, tag),
    constraint fk_content_tags_content foreign key (content_id) references content_items(id) on delete cascade
);

create table content_recommend_words (
    content_id varchar(64) not null,
    word varchar(80) not null,
    sort_order int not null default 0,
    primary key (content_id, word),
    constraint fk_content_words_content foreign key (content_id) references content_items(id) on delete cascade
);

create table media_assets (
    id bigint generated by default as identity primary key,
    content_id varchar(64) not null,
    kind varchar(20) not null,
    url text not null,
    storage_key varchar(255),
    mime_type varchar(100),
    file_size bigint,
    width int,
    height int,
    duration_ms bigint,
    quality varchar(20),
    sort_order int not null default 0,
    created_at timestamp not null default current_timestamp,
    constraint fk_media_content foreign key (content_id) references content_items(id) on delete cascade
);

create table content_stats (
    content_id varchar(64) primary key,
    like_count int not null default 0,
    comment_count int not null default 0,
    favorite_count int not null default 0,
    share_count int not null default 0,
    view_count int not null default 0,
    constraint fk_stats_content foreign key (content_id) references content_items(id) on delete cascade
);

create table comments (
    id varchar(64) primary key,
    content_id varchar(64) not null,
    user_id varchar(64) not null,
    parent_id varchar(64),
    body text not null,
    like_count int not null default 0,
    source varchar(30) not null default 'app',
    status varchar(20) not null default 'visible',
    created_at timestamp not null default current_timestamp,
    constraint fk_comments_content foreign key (content_id) references content_items(id) on delete cascade,
    constraint fk_comments_user foreign key (user_id) references users(id) on delete cascade,
    constraint fk_comments_parent foreign key (parent_id) references comments(id) on delete cascade
);

create table content_likes (
    content_id varchar(64) not null,
    user_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    primary key (content_id, user_id),
    constraint fk_content_likes_content foreign key (content_id) references content_items(id) on delete cascade,
    constraint fk_content_likes_user foreign key (user_id) references users(id) on delete cascade
);

create table comment_likes (
    comment_id varchar(64) not null,
    user_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    primary key (comment_id, user_id),
    constraint fk_comment_likes_comment foreign key (comment_id) references comments(id) on delete cascade,
    constraint fk_comment_likes_user foreign key (user_id) references users(id) on delete cascade
);

create table collections (
    id varchar(64) primary key,
    user_id varchar(64) not null,
    name varchar(80) not null,
    is_default boolean not null default false,
    created_at timestamp not null default current_timestamp,
    constraint fk_collections_user foreign key (user_id) references users(id) on delete cascade
);

create table collection_items (
    collection_id varchar(64) not null,
    content_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    primary key (collection_id, content_id),
    constraint fk_collection_items_collection foreign key (collection_id) references collections(id) on delete cascade,
    constraint fk_collection_items_content foreign key (content_id) references content_items(id) on delete cascade
);

create table follows (
    follower_id varchar(64) not null,
    following_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    primary key (follower_id, following_id),
    constraint fk_follows_follower foreign key (follower_id) references users(id) on delete cascade,
    constraint fk_follows_following foreign key (following_id) references users(id) on delete cascade,
    constraint ck_follows_not_self check (follower_id <> following_id)
);

create table notifications (
    id varchar(64) primary key,
    receiver_user_id varchar(64) not null,
    actor_user_id varchar(64),
    type varchar(40) not null,
    content_id varchar(64),
    comment_id varchar(64),
    message varchar(255) not null,
    read_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint fk_notifications_receiver foreign key (receiver_user_id) references users(id) on delete cascade,
    constraint fk_notifications_actor foreign key (actor_user_id) references users(id) on delete set null,
    constraint fk_notifications_content foreign key (content_id) references content_items(id) on delete cascade,
    constraint fk_notifications_comment foreign key (comment_id) references comments(id) on delete cascade
);

create table outbox_events (
    id varchar(64) primary key,
    event_type varchar(80) not null,
    aggregate_type varchar(50) not null,
    aggregate_id varchar(64) not null,
    payload_json text not null,
    status varchar(20) not null default 'pending',
    retry_count int not null default 0,
    created_at timestamp not null default current_timestamp,
    processed_at timestamp,
    last_error text
);

create index idx_content_items_type on content_items(type);
create index idx_content_items_author on content_items(author_user_id, publish_time desc);
create index idx_comments_content_created on comments(content_id, created_at desc);
create index idx_comments_parent on comments(parent_id);
create index idx_content_likes_user on content_likes(user_id);
create index idx_collection_items_content on collection_items(content_id);
create index idx_follows_following on follows(following_id);
create index idx_notifications_receiver_created on notifications(receiver_user_id, created_at desc);
create index idx_outbox_status_created on outbox_events(status, created_at);